### ISSUE TITLE
Should have a config file to specify server list, rather than hard-coding it

### ISSUE THREAD

**Issue by garyo** [garyo/lsp-multiplexer#4]
Then use a cmd-line option to specify the config file.

**Comment by imprvhub** [comment]
hi @garyo can i be assigned to this issue?

**Comment by garyo** [comment]
> hi @garyo can i be assigned to this issue?

Thanks!

**Comment by imprvhub** [comment]
@garyo there's a PR pending for review. Please let me know if you want any changes.
Thanks!
